### ISSUE TITLE
inverting background and text and leave images untouched

### ISSUE THREAD

**Issue by zekekin** [stT-e5gna2z5MBS/invert-pdf#1]
Hi there,

I was looking for a package that would invert just the background and text, and leave images untouched. Would this be possible with small adjustments to the current codebase? 

Thanks!

**Comment by stT-e5gna2z5MBS** [comment]
invert everything using:
`gswin64c -o tempWork\yourfileoutput.pdf -sDEVICE=pdfwrite -c "{1 exch sub}{1 exch sub}{1 exch sub}{1 exch sub} setcolortransfer" -f tempWork\compressed.pdf`

logic (^ for invert):
* images
* background and text

->(use this package)
* ^images
* background and text

->(invert everything)
* ^^images
* ^background and text

<=> (two inverts cancel out)
* images
* ^background and text

**Comment by zekekin** [comment]
Got it! Thank you for your help!
